<?php

/**
 * BaseSupplier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $soundexvalue
 * @property Doctrine_Collection $Orders
 * @property Doctrine_Collection $Aliases
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getSoundexvalue() Returns the current record's "soundexvalue" value
 * @method Doctrine_Collection getOrders()       Returns the current record's "Orders" collection
 * @method Doctrine_Collection getAliases()      Returns the current record's "Aliases" collection
 * @method Supplier            setId()           Sets the current record's "id" value
 * @method Supplier            setName()         Sets the current record's "name" value
 * @method Supplier            setSoundexvalue() Sets the current record's "soundexvalue" value
 * @method Supplier            setOrders()       Sets the current record's "Orders" collection
 * @method Supplier            setAliases()      Sets the current record's "Aliases" collection
 * 
 * @package    myshelf
 * @subpackage model
 * @author     Adam Jennison
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseSupplier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('supplier');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('soundexvalue', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Spend as Orders', array(
             'local' => 'id',
             'foreign' => 'supplier_id'));

        $this->hasMany('Supplieralias as Aliases', array(
             'local' => 'id',
             'foreign' => 'supplier_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}