<?php

/**
 * BaseService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $soundexvalue
 * @property integer $directorate_id
 * @property Directorate $directorate
 * @property Doctrine_Collection $Supplier
 * @property Doctrine_Collection $Servicespend
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getSoundexvalue()   Returns the current record's "soundexvalue" value
 * @method integer             getDirectorateId()  Returns the current record's "directorate_id" value
 * @method Directorate         getDirectorate()    Returns the current record's "directorate" value
 * @method Doctrine_Collection getSupplier()       Returns the current record's "Supplier" collection
 * @method Doctrine_Collection getServicespend()   Returns the current record's "Servicespend" collection
 * @method Service             setId()             Sets the current record's "id" value
 * @method Service             setName()           Sets the current record's "name" value
 * @method Service             setSoundexvalue()   Sets the current record's "soundexvalue" value
 * @method Service             setDirectorateId()  Sets the current record's "directorate_id" value
 * @method Service             setDirectorate()    Sets the current record's "directorate" value
 * @method Service             setSupplier()       Sets the current record's "Supplier" collection
 * @method Service             setServicespend()   Sets the current record's "Servicespend" collection
 * 
 * @package    myshelf
 * @subpackage model
 * @author     Adam Jennison
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseService extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('service');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('soundexvalue', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('directorate_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Directorate as directorate', array(
             'local' => 'directorate_id',
             'foreign' => 'id'));

        $this->hasMany('Supplier', array(
             'refClass' => 'Spend',
             'local' => 'service_id',
             'foreign' => 'supplier_id'));

        $this->hasMany('Spend as Servicespend', array(
             'local' => 'id',
             'foreign' => 'service_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}