<?php

/**
 * BaseDirectorate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $soundexvalue
 * @property Doctrine_Collection $Payments
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getSoundexvalue() Returns the current record's "soundexvalue" value
 * @method Doctrine_Collection getPayments()     Returns the current record's "Payments" collection
 * @method Directorate         setId()           Sets the current record's "id" value
 * @method Directorate         setName()         Sets the current record's "name" value
 * @method Directorate         setSoundexvalue() Sets the current record's "soundexvalue" value
 * @method Directorate         setPayments()     Sets the current record's "Payments" collection
 * 
 * @package    myshelf
 * @subpackage model
 * @author     Adam Jennison
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDirectorate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('directorate');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('soundexvalue', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Spend as Payments', array(
             'local' => 'id',
             'foreign' => 'directorate_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'unique' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}