<?php

/**
 * Directorate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    myshelf
 * @subpackage model
 * @author     Adam Jennison
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Directorate extends BaseDirectorate
{
}
