<?php

/**
 * DirectorateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DirectorateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DirectorateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Directorate');
    }
    
    public static function getNumberOfDirectorates(){
        
                $connection = Doctrine_Manager::connection();
        $query = 'SELECT count(name) as total from directorate';
        $statement=$connection->execute($query);
        $statement->execute();
        $resultset=$statement->fetch(PDO::FETCH_OBJ);
        $total=$resultset->total;
        return $total;
    }    
    

}
