<?php

/**
 * DirectorateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DirectorateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DirectorateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Directorate');
    }
}