<?php

/**
 * Service
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    myshelf
 * @subpackage model
 * @author     Adam Jennison
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Service extends BaseService
{
  
  public function getTotalSpent(){
         $connection = Doctrine_Manager::connection();
        $query = 'SELECT sum(amount) as total from spend where service_id='.$this->getId();
        $statement=$connection->execute($query);
        $statement->execute();
        $resultset=$statement->fetch(PDO::FETCH_OBJ);
        $total=$resultset->total;
        return $total;
  }
  
  
}
