<?php

/**
 * SpendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Spend');
    }
}