<?php

/**
 * Supplier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    myshelf
 * @subpackage model
 * @author     Adam Jennison
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Supplier extends BaseSupplier
{
  
  public function getSpendByService($serviceId){
      $q=Doctrine_Core::getTable('Spend')
	   ->createQuery('s')
	   ->where('s.supplier_id=?',$this->getId())
	   ->andWhere('s.service_id=?',$service_id);
     
      return $q->execute();
  }
  
    public function getTotalSpendByService($serviceId){
         $connection = Doctrine_Manager::connection();
        $query = 'SELECT sum(amount) as total from spend where (service_id='.$serviceId.' and supplier_id='.$this->getId().')';
        $statement=$connection->execute($query);
        $statement->execute();
        $resultset=$statement->fetch(PDO::FETCH_OBJ);
        $total=$resultset->total;
        return $total;
  }

    public function getCountSpendByService($serviceId){
         $connection = Doctrine_Manager::connection();
        $query = 'SELECT count(amount) as total from spend where (service_id='.$serviceId.' and supplier_id='.$this->getId().')';
        $statement=$connection->execute($query);
        $statement->execute();
        $resultset=$statement->fetch(PDO::FETCH_OBJ);
        $total=$resultset->total;
        return $total;
  }  
  
}
