<?php

/**
 * SupplieraliasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SupplieraliasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SupplieraliasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Supplieralias');
    }
}