<?php

/**
 * SupplierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SupplierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SupplierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Supplier');
    }
}