<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('itemgroup_fz_tag', 'itemgroup_fz_tag_tag_id_fz_tag_id', array(
             'name' => 'itemgroup_fz_tag_tag_id_fz_tag_id',
             'local' => 'tag_id',
             'foreign' => 'id',
             'foreignTable' => 'fz_tag',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('itemgroup_fz_tag', 'itemgroup_fz_tag_id_itemgroup_id', array(
             'name' => 'itemgroup_fz_tag_id_itemgroup_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'itemgroup',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('itemgroup_fz_tag', 'itemgroup_fz_tag_tag_id', array(
             'fields' => 
             array(
              0 => 'tag_id',
             ),
             ));
        $this->addIndex('itemgroup_fz_tag', 'itemgroup_fz_tag_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('itemgroup_fz_tag', 'itemgroup_fz_tag_tag_id_fz_tag_id');
        $this->dropForeignKey('itemgroup_fz_tag', 'itemgroup_fz_tag_id_itemgroup_id');
        $this->removeIndex('itemgroup_fz_tag', 'itemgroup_fz_tag_tag_id', array(
             'fields' => 
             array(
              0 => 'tag_id',
             ),
             ));
        $this->removeIndex('itemgroup_fz_tag', 'itemgroup_fz_tag_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}