<?php

/**
 * fzTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fzTagTable extends PluginfzTagTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object fzTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fzTag');
    }
}